name: MSBuild

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'Images/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'Images/**'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release, Debug]
        
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore ./Game/Game.sln

    - name: Build
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=x86 ./Game/Game.sln
      
    - name: Run tests
      if: matrix.configuration == 'Release'
      run: ./Game/Release/logging_test.exe
    
